#Database
DB_USERNAME: root
DB_PASSWORD: 1234
MYSQL_HOST: localhost
MYSQL_PORT: 3306
MYSQL_DATABASE: thevergov_db

#Server
CONTAINER_PORT: 8080
ACTIVE_PROFILE: prod

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID:
EMAIL_PASSWORD:
VERIFY_EMAIL_HOST: http://localhost:8080



JWT_EXPIRATION: 432_000_000
JWT_SECRET: ${SECRET}